import type { Product } from '../types';

export const DEMO_PRODUCTS: Product[] = [
    {
        id: 1,
        title: 'Écouteurs Premium Bluetooth',
        description: 'Écouteurs sans fil avec réduction active du bruit, batterie 40h',
        price: 150,
        discount_price: 99.99,
        image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400',
        category: 'Électronique',
        rating: 4.8,
        reviews_count: 245,
        in_stock: true,
        views: 1200,
    },
    {
        id: 2,
        title: 'Montre Intelligente Fitness',
        description: 'Suivi de santé complet avec GPS et moniteur cardiaque',
        price: 200,
        image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400',
        category: 'Électronique',
        rating: 4.5,
        reviews_count: 189,
        in_stock: true,
        views: 950,
    },
    {
        id: 3,
        title: 'Clavier Mécanique Gaming',
        description: 'Clavier RGB avec switches méchaniques haute performance',
        price: 120,
        discount_price: 89.99,
        image: 'https://images.unsplash.com/photo-1587829191301-4e7e0c9aa52a?w=400',
        category: 'Informatique',
        rating: 4.6,
        reviews_count: 156,
        in_stock: true,
        views: 800,
    },
    {
        id: 4,
        title: 'Souris Sans Fil Ergonomique',
        description: 'Souris avec design ergonomique et batterie longue durée',
        price: 45,
        image: 'https://images.unsplash.com/photo-1527814050087-3793815479db?w=400',
        category: 'Informatique',
        rating: 4.3,
        reviews_count: 98,
        in_stock: true,
        views: 600,
    },
    {
        id: 5,
        title: 'Caméra Webcam 4K',
        description: 'Webcam ultra HD avec microphone stéréo intégré',
        price: 80,
        image: 'https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=400',
        category: 'Électronique',
        rating: 4.4,
        reviews_count: 124,
        in_stock: true,
        views: 700,
    },
    {
        id: 6,
        title: 'Hub USB Multiprise',
        description: '7 ports USB 3.0 avec alimentation externe',
        price: 35,
        discount_price: 24.99,
        image: 'https://images.unsplash.com/photo-1625948515291-69613efd103f?w=400',
        category: 'Accessoires',
        rating: 4.2,
        reviews_count: 67,
        in_stock: true,
        views: 400,
    },
    {
        id: 7,
        title: 'Batterie Externe 30000mAh',
        description: 'Batterie portable ultra-rapide pour recharger 3 appareils',
        price: 60,
        image: 'https://images.unsplash.com/photo-1591936281775-20f5bca3c04a?w=400',
        category: 'Accessoires',
        rating: 4.7,
        reviews_count: 203,
        in_stock: true,
        views: 1100,
    },
    {
        id: 8,
        title: 'Câble USB-C Premium',
        description: 'Câble robuste 3m, charge rapide et transfert de données',
        price: 20,
        image: 'https://images.unsplash.com/photo-1609042240b552-27ec51f514ca?w=400',
        category: 'Accessoires',
        rating: 4.5,
        reviews_count: 156,
        in_stock: true,
        views: 300,
    },
    {
        id: 9,
        title: 'Micro pour Streaming',
        description: 'Microphone USB cardioïde avec bras de suspension',
        price: 140,
        discount_price: 109.99,
        image: 'https://images.unsplash.com/photo-1598899134739-24c46f58b8c0?w=400',
        category: 'Électronique',
        rating: 4.9,
        reviews_count: 312,
        in_stock: false,
        views: 1500,
    },
];
